---
- name: Update Homebrew
  homebrew: name=null state=absent update_homebrew=yes
  when: homebrew_update

- name: Install formulas via Homebrew
  homebrew: name={{ item.name }} install_options={{ item.options | default() }} state=upgraded
  with_items: brews

- name: Install casks via Homebrew cask
  homebrew_cask: name={{ item }} state=installed
  with_items: casks
  environment: cask_env